
package Tampilan;

import com.stripbandunk.jwidget.JDynamicTable;
import com.stripbandunk.jwidget.model.DynamicTableModel;
import entity.makanan;
import java.util.List;
import Service.makanan_service;
import javax.swing.JOptionPane;
import Tampilan.Menu_utama;


public class From_makanan extends javax.swing.JFrame {

    private DynamicTableModel<makanan> tablemodel;
    private JDynamicTable jDynamictable;
   
    
private void reload(){
    tablemodel.clear();
    makanan_service service =new makanan_service();
    List<makanan>list =service.Tampil();
    for(makanan pel : list){
        tablemodel.add(pel);
    }
}
    public From_makanan() {
        initComponents();
        tablemodel = new DynamicTableModel<>(makanan.class);
        jDynamictable= new JDynamicTable(tablemodel);
        jScrollPane1.setViewportView(jDynamictable);
    reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        B_ubah = new javax.swing.JButton();
        B_Kembali = new javax.swing.JButton();
        B_hapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        T_harga = new javax.swing.JTextField();
        T_Nama = new javax.swing.JTextField();
        T_kode = new javax.swing.JTextField();
        B_Tambah = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        B_ubah.setBackground(new java.awt.Color(0, 102, 102));
        B_ubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_ubah.setForeground(new java.awt.Color(255, 255, 255));
        B_ubah.setText("Ubah");
        B_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ubahActionPerformed(evt);
            }
        });

        B_Kembali.setBackground(new java.awt.Color(255, 51, 51));
        B_Kembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B_Kembali.setForeground(new java.awt.Color(255, 255, 255));
        B_Kembali.setText("x");
        B_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_KembaliActionPerformed(evt);
            }
        });

        B_hapus.setBackground(new java.awt.Color(0, 102, 102));
        B_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_hapus.setForeground(new java.awt.Color(255, 255, 255));
        B_hapus.setText("Hapus");
        B_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_hapusActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Kode Menu");

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Nama Menu");

        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Harga");

        B_Tambah.setBackground(new java.awt.Color(0, 102, 102));
        B_Tambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_Tambah.setForeground(new java.awt.Color(255, 255, 255));
        B_Tambah.setText("Tambah");
        B_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_TambahActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("FROM MENU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(B_Tambah)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(T_kode, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(T_Nama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(T_harga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B_ubah)
                        .addGap(27, 27, 27)
                        .addComponent(B_hapus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B_Kembali)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Kembali)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(T_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(T_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(T_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_ubah)
                            .addComponent(B_hapus)
                            .addComponent(B_Tambah))))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_hapusActionPerformed
     if(jDynamictable.getSelectedRow()!=-1){
    if(JOptionPane.showConfirmDialog(this, "Anda Yaking Akan Menghapus Data?","Hapus barang",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
        int index = jDynamictable.convertColumnIndexToModel(jDynamictable.getSelectedRow());
        makanan pel = tablemodel.get(index);
        System.out.println(pel.getId_makanan());
        makanan_service service = new makanan_service();
        service.delete_paket(pel.getId_makanan());
    }
}else{
    JOptionPane.showMessageDialog(this, "Sillahkan pilih data yang akan dihapus terlebih dahulu");
}
reload();
        // TODO add your handling code here:
    }//GEN-LAST:event_B_hapusActionPerformed

    private void B_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_KembaliActionPerformed
Menu_utama utama = new Menu_utama();
utama.setVisible(true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_B_KembaliActionPerformed

    private void B_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_TambahActionPerformed
makanan pel = new makanan();

pel.setKode_makanan(T_kode.getText());
pel.setNama_makanan(T_Nama.getText());
pel.setHarga(Integer.parseInt(T_harga.getText()));

makanan_service kar = new makanan_service();
kar.insertproduk(pel);
reload();
T_kode.setText("");
T_Nama.setText("");
T_harga.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_B_TambahActionPerformed

    private void B_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ubahActionPerformed
if (jDynamictable.getSelectedRow() != -1) {
    // Ambil indeks baris yang dipilih
    int rowIndex = jDynamictable.getSelectedRow();
    
    // Ambil data dari model berdasarkan indeks baris
    makanan makan = tablemodel.get(rowIndex); // pastikan tablemodel adalah list atau array yang mendukung get(index)
    
    // Buka dialog untuk mengubah data
    ubah_makanan updat = new ubah_makanan(this, true);
    updat.Update_makanan(makan); // kirim objek 'makan' untuk diubah
    reload(); // fungsi untuk memuat ulang data
} else {
    JOptionPane.showMessageDialog(this, "Silahkan pilih data yang ingin dirubah");
}


        // TODO add your handling code here:
    }//GEN-LAST:event_B_ubahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(From_makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(From_makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(From_makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(From_makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new From_makanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Kembali;
    private javax.swing.JButton B_Tambah;
    private javax.swing.JButton B_hapus;
    private javax.swing.JButton B_ubah;
    private javax.swing.JTextField T_Nama;
    private javax.swing.JTextField T_harga;
    private javax.swing.JTextField T_kode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
